//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nalazi()
        {
            this.Sastojis = new HashSet<Sastoji>();
        }
    
        public int MagacinMaterijalaIdObj { get; set; }
        public int MagacinMaterijalaIndustrijaObuceIdIO { get; set; }
        public int MaterijalIdMat { get; set; }
    
        public virtual MagacinMaterijala MagacinMaterijala { get; set; }
        public virtual Materijal Materijal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sastoji> Sastojis { get; set; }
    }
}
