//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objekat
    {
        public int IdObj { get; set; }
        public string NazObj { get; set; }
        public string AdrObj { get; set; }
        public int GradIdG { get; set; }
        public int IndustrijaObuceIdIO { get; set; }
        public string TipObj { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual IndustrijaObuce IndustrijaObuce { get; set; }
    }
}
