//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sastoji
    {
        public int NalaziMagacinMaterijalaIdObj { get; set; }
        public int NalaziMagacinMaterijalaIndustrijaObuceIdIO { get; set; }
        public int NalaziMaterijalIdMat { get; set; }
        public int ObucaIdOb { get; set; }
    
        public virtual Nalazi Nalazi { get; set; }
        public virtual Obuca Obuca { get; set; }
    }
}
